In [1]:
import pandas as pd

df_names = pd.read_csv('https://datasets.imdbws.com/name.basics.tsv.gz', sep="\t")
df_titles_akas = pd.read_csv("https://datasets.imdbws.com/title.akas.tsv.gz",sep="\t")
df_titles_basic = pd.read_csv("https://datasets.imdbws.com/title.basics.tsv.gz",sep="\t")
df_titles_crews = pd.read_csv("https://datasets.imdbws.com/title.crew.tsv.gz",sep="\t")
df_titles_episode = pd.read_csv("https://datasets.imdbws.com/title.episode.tsv.gz",sep="\t")
df_titles_principal = pd.read_csv("https://datasets.imdbws.com/title.principals.tsv.gz",sep="\t")
df_titles_ratings = pd.read_csv("https://datasets.imdbws.com/title.ratings.tsv.gz",sep="\t")

C:\Users\andre\AppData\Local\Temp\ipykernel_22940\2420424901.py:5: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_titles_basic = pd.read_csv("https://datasets.imdbws.com/title.basics.tsv.gz",sep="\t")

In [2]:
# Afficher df_names
df_names.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0053137,tt0027125"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack,archive_footage","tt0037382,tt0075213,tt0117057,tt0038355"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0083922,tt0050976,tt0069467"

In [3]:
# Afficher f_titles_akas 
df_titles_akas.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita,\N,\N,original,\N,1
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita,US,\N,imdbDisplay,\N,0
3,tt0000001,4,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
4,tt0000001,5,Καρμενσίτα,GR,\N,imdbDisplay,\N,0

In [4]:
# Afficher df_titles_basic
df_titles_basic

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
10682456,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,"Action,Drama,Family"
10682457,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
10682458,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
10682459,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
10682460,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [5]:
# Afficher df_titles_crews
df_titles_crews.head()

      tconst  directors writers
0  tt0000001  nm0005690      \N
1  tt0000002  nm0721526      \N
2  tt0000003  nm0721526      \N
3  tt0000004  nm0721526      \N
4  tt0000005  nm0005690      \N

In [6]:
# Afficher df_titles_episode
df_titles_episode.head()

      tconst parentTconst seasonNumber episodeNumber
0  tt0041951    tt0041038            1             9
1  tt0042816    tt0989125            1            17
2  tt0042889    tt0989125           \N            \N
3  tt0043426    tt0040051            3            42
4  tt0043631    tt0989125            2            16

In [7]:
# Afficher df_titles_principal
df_titles_principal.head(50)

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N
5,tt0000002,2,nm1335271,composer,\N,\N
6,tt0000003,1,nm0721526,director,\N,\N
7,tt0000003,2,nm1770680,producer,producer,\N
8,tt0000003,3,nm0721526,producer,producer,\N
9,tt0000003,4,nm1335271,composer,\N,\N
10,tt0000003,5,nm5442200,editor,editor,\N
11,tt0000004,1,nm0721526,director,\N,\N
12,tt0000004,2,nm1335271,composer,\N,\N
13,tt0000005,1,nm0443482,actor,\N,"[""Blacksmith""]"
14,tt0000005,2,nm0653042,actor,\N,"[""Assistant""]"
15,tt0000005,3,nm0249379,producer,producer,\N
16,tt0000007,1,nm0179163,actor,\N,\N
17,tt0000007,2,nm0183947,actor,\N,\N
18,tt0000007,3,nm0005690,director,\N,\N
19,tt0000007,4,nm0374658,director,\N,\N
20,tt0000007,5,nm0005690,producer,producer,\N
21,tt0000007,6,nm0249379,producer,producer,\N
22,tt0000007,7,nm0374658,cinematographer,\N,\N
23,tt0000008,1,nm0653028,actor,\N,"[""Sneezing Man""]"
24,tt0000008,2,nm0005690,director,\N,\N
25,tt0000008,3,nm0005690,producer,producer,\N
26,tt0000008,4,nm0374658,cinematographer,\N,\N
27,tt0000009,1,nm0063086,actress,\N,"[""Miss Geraldine Holbrook (Miss Jerry)""]"
28,tt0000009,2,nm0183823,actor,\N,"[""Mr. Hamilton""]"
29,tt0000009,3,nm1309758,actor,\N,"[""Chauncey Depew - the Director of the New Yor..."
30,tt0000009,4,nm0085156,director,\N,\N
31,tt0000009,5,nm0085156,writer,\N,\N
32,tt0000009,6,nm0085156,producer,producer,\N
33,tt0000009,7,nm0085156,cinematographer,\N,\N
34,tt0000010,1,nm0525910,director,\N,\N
35,tt0000010,2,nm0525910,producer,producer,\N
36,tt0000010,3,nm0525910,cinematographer,\N,\N
37,tt0000011,1,nm3692297,actor,\N,"[""Acrobats""]"
38,tt0000011,2,nm0804434,director,\N,\N
39,tt0000011,3,nm0804434,producer,producer,\N
40,tt0000011,4,nm0804434,cinematographer,\N,\N
41,tt0000012,1,nm2880396,self,\N,"[""Self""]"
42,tt0000012,2,nm9735580,self,\N,"[""Self""]"
43,tt0000012,3,nm0525900,self,\N,"[""Self""]"
44,tt0000012,4,nm9735581,self,\N,"[""Self""]"
45,tt0000012,5,nm9735579,self,\N,"[""Self""]"
46,tt0000012,6,nm9653419,self,\N,"[""Self""]"
47,tt0000012,7,nm0525908,director,\N,\N
48,tt0000012,8,nm0525910,director,\N,\N
49,tt0000012,9,nm0525908,producer,producer,\N

In [8]:
# Afficher df_titles_ratings
df_titles_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2041
1  tt0000002            5.7       273
2  tt0000003            6.5      1997
3  tt0000004            5.4       178
4  tt0000005            6.2      2757

In [ ]:
print('ulrich')